/**
 * Normalization for network device configs.
 *
 * Devices are chatty: timestamps, uptime counters, line wrapping, and ordering
 * that shifts without meaning changing. Diffing raw output gives you noise, so
 * everything gets canonicalized before comparison.
 */

const NOISE_PATTERNS = [
  // "!Last configuration change at 23:37:30 UTC Mon Oct 6 2026"
  /^!.*(last configuration change|commit time|generated by).*$/i,
  // "Building configuration... / Current configuration : 82 bytes"
  /^\s*(building configuration|current configuration|nvram size|configuration register size).*$/i,
  /^\s*\d+\s+bytes?\s*$/i,
  // Cisco uptime footer/header
  /^.*uptime is.*$/i,
  /^.*clock\s+(is|set).*$/i,
  // "R1#show run" style command echoes
  /^\s*[a-z0-9._-]+[>#]\s*show\s+.*$/i,
  // Last config change counters
  /^\s*!\s*last\s+config/i,
];

export function stripNoise(lines) {
  return lines.filter((line) => !NOISE_PATTERNS.some((p) => p.test(line)));
}

function canonicalizeLine(line) {
  return line
    .replace(/\s+/g, " ")
    .replace(/\s*([{}[\]])\s*/g, "$1")
    .trim();
}

/**
 * Canonicalize a full config into comparable lines.
 *
 * Order is deliberately PRESERVED. In network configuration, sequence is
 * meaning: ACL entries, static routes, and prefix lists are evaluated in order,
 * so a reordered config is a genuinely different config and must read as drift.
 * Only true duplicates are collapsed.
 */
export function normalize(raw) {
  const lines = String(raw).replace(/\r\n/g, "\n").split("\n");

  const cleaned = stripNoise(lines)
    .filter((l) => l.trim() !== "" && l.trim() !== "!")
    .map(canonicalizeLine)
    .filter((l) => l.length > 0);

  const seen = new Set();
  const out = [];
  for (const line of cleaned) {
    if (seen.has(line)) continue;
    seen.add(line);
    out.push(line);
  }
  return out;
}

/**
 * Lines that are safe to ignore entirely when deciding whether a device drifted.
 * These are runtime facts, not configuration intent.
 */
const RUNTIME_ONLY = [
  /^\s*interface\s+\S+$/i,
  /^\s*(ip route|ip address|router ospf|network\s)/i,
];

export function isIntentional(line) {
  return !RUNTIME_ONLY.some((p) => p.test(line));
}

export default { normalize, stripNoise, canonicalizeLine, isIntentional };